plugins:
  - 'prettier-plugin-svelte'

arrowParens: always
bracketSpacing: true
jsxSingleQuote: true
printWidth: 160
semi: true
singleQuote: true
svelteSortOrder: options-scripts-markup-styles
tabWidth: 2
trailingComma: all
useTabs: true
endOfLine: auto
